EasyBlog/Models/ErrorViewModel.cs
namespace EasyBlog.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

EasyBlog/Areas/Admin/Controllers/AdminBaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EasyBlog.Areas.Admin.Controllers
{
	[Authorize(Roles = "Administrator")]
	[Area("Admin")]
	public abstract class AdminBaseController : Controller
	{
	}
}

EasyBlog/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EasyBlog.Areas.Admin.Controllers
{
	
	public class DashboardController : AdminBaseController
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

EasyBlog/Controllers/HomeController.cs
using EasyBlog.Data;
using EasyBlog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EasyBlog.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly ApplicationDbContext _db;

		public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
		{
			_logger = logger;
			_db = db;
		}

		public IActionResult Index(int? cid)
		{
			IQueryable<Post> posts = _db.Posts;

			if (cid != null)
			{
				posts = posts.Where(p => p.CategoryId == cid);
				ViewBag.CategoryName = _db.Categories.Find(cid)?.Name;
			}

			return View(posts.OrderByDescending(x => x.Id).ToList());
		}

		[Route("Post/{id:int}")]
		public IActionResult ShowPost(int id)
		{
			var post = _db.Posts
				.Include(x => x.Category)
				.FirstOrDefault(x => x.Id == id);

			if( post == null)
			{
				return NotFound();
			}

			return View(post);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

EasyBlog/ViewComponents/SidebarCategoriesViewComponent.cs
using EasyBlog.Data;
using Microsoft.AspNetCore.Mvc;

namespace EasyBlog.ViewComponents
{
	public class SidebarCategoriesViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
	{
		private readonly ApplicationDbContext _db;

		public SidebarCategoriesViewComponent(ApplicationDbContext db)
        {
			_db = db;
		}

        public IViewComponentResult Invoke()
		{
			return View(_db.Categories.ToList());
		}
	}
}

EasyBlog/Areas/Admin/Views/Dashboard/Index.cshtml
@{
	ViewBag.Title = "Dashboard";
}

<h1>@ViewBag.Title</h1>

EasyBlog/Views/Home/Index.cshtml
@model List<Post>
@{
	ViewData["Title"] = "Home Page";
}

@if (ViewBag.CategoryName != null)
{
	<h2 class="border-bottom pb-3 mb-4">Posts in the &ldquo;@ViewBag.CategoryName&ldquo; Category</h2>
}

@foreach (var post in Model)
{
	<div class="card mb-4">
		<a href="#!"><img class="card-img-top post-image" src="~/img/posts/@post.Image" alt="@post.Title" /></a>
		<div class="card-body">
			@* <div class="small text-muted">January 1, 2023</div> *@
			<h2 class="card-title">@post.Title</h2>
			<p class="card-text">@post.Description</p>
			@* <a class="btn btn-primary" href="#!">Read more →</a> *@
			<a class="btn btn-primary" asp-action="ShowPost" asp-route-id="@post.Id">Read more →</a>
		</div>
	</div>
}


<!-- Pagination-->
<nav aria-label="Pagination">
	<hr class="my-0" />
	<ul class="pagination justify-content-center my-4">
		<li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
		<li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
		<li class="page-item"><a class="page-link" href="#!">2</a></li>
		<li class="page-item"><a class="page-link" href="#!">3</a></li>
		<li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
		<li class="page-item"><a class="page-link" href="#!">15</a></li>
		<li class="page-item"><a class="page-link" href="#!">Older</a></li>
	</ul>
</nav>

EasyBlog/Views/Home/ShowPost.cshtml
@model Post
@{
	ViewBag.Title =Model.Title;
}
<!-- Post content-->
<article>
	<!-- Post header-->
	<header class="mb-4">
		<!-- Post title-->
		<h1 class="fw-bolder mb-1">Welcome to @Model.Title</h1>
		<!-- Post meta content-->
		@* <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div> *@ <!-- Post categories-->
		<a class="badge bg-secondary text-decoration-none link-light" asp-controller="Home" asp-action="Index" asp-route-cid="@Model.Category. Id">@Model.Category.Name</a>
	</header>
	<!-- Preview image figure-->
	<figure class="mb-4">
		<img class="img-fluid rounded post-image" src="~/img/posts/@Model.Image" alt="@Model.Title" />
	</figure>
	<!-- Post content-->
	<section class="mb-5">
		@Html.Raw(Model.Content)
	</section>
</article>

EasyBlog/Views/Shared/Components/SidebarCategories/Default.cshtml
@model List<Category>

<ul class="list-unstyled mb-0">
	@foreach (var c in Model)
	{
		<li><a asp-controller="Home" asp-action="Index" asp-route-cid="@c.Id">@c.Name</a></li>
	}
</ul>

EasyBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="Sample Blog Website" />
	<meta name="author" content="Mehmed Tarık ÇAMLI" />
	<title>@ViewBag.Title - Easy Blog</title>
	<!-- Favicon-->
	<link rel="icon" type="image/x-icon" href="~/favicon.ico" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="~/css/styles.css" rel="stylesheet" />
	<link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
	<!-- Responsive navbar-->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" asp-controller="Home" asp-action="Index">Easy Blog</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
					<li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
				</ul>
				<partial name="_LoginPartial" />
			</div>
		</div>
	</nav>
	<!-- Page content-->
	<div class="container pt-4">
		<div class="row">
			<!-- Blog entries-->
			<div class="col-lg-8">
				@RenderBody()
			</div>
			<!-- Side widgets-->
			<div class="col-lg-4">
				<!-- Search widget-->
				<div class="card mb-4">
					<div class="card-header">Search</div>
					<div class="card-body">
						<div class="input-group">
							<input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
							<button class="btn btn-primary" id="button-search" type="button">Go!</button>
						</div>
					</div>
				</div>
				<!-- Categories widget-->
				<div class="card mb-4">
					<div class="card-header">Categories</div>
					<div class="card-body">
						<vc:sidebar-categories />
					</div>
				</div>
				<!-- Side widget-->
				<div class="card mb-4">
					<div class="card-header">About Me</div>
					<div class="card-body">
						Welcome to my blog! I'm a curious explorer, avid reader,
						and passionate writer, sharing insights and stories from my adventures.
						Join me on this journey of discovery and inspiration.
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer-->
	<footer class="py-5 bg-dark mt-auto">
		<div class="container"><p class="m-0 text-center text-white">Copyright &copy; Easy Blog 2024</p></div>
	</footer>
	<!-- Bootstrap core JS-->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<!-- Core theme JS-->
	<script src="~/js/site.js"></script>
	@await RenderSectionAsync("Scripts", false)
</body>
</html>